- .github/PULL_REQUEST_TEMPLATE.md
Updated PR Template with syntax to link the workitems from Azure Boards
> [AB#36304] docs: :memo: update PR template

- src/scenarios/user-authentication/ResetPasswordWithAxAuth/ResetPasswordWithAxAuth.tsx
- src/scenarios/user-authentication/SignUpWithAxAuth/SignUpWithAxAuth.tsx
Rename all occurrences of consumer to end-user
> [AB#36040] refactor: :recycle: rename occurrences of consumer to end-user

- .adops/build-pipeline.yml
Add build pipeline to build and push Docker image of fe-build samples through Azure DevOps.
> [AB#36258] feat: 🏷️ adjust release pipelines for fe samples

- package.json
- yarn.lock
[[AB#37013](https://dev.azure.com/axinom/5e61ad7f-f562-45f3-8078-9ade7df639c1/_workitems/edit/37013)] mosaic fe sample host lib version upgrade
Add latest fe sample host version
> feat: mosaic fe sample host lib version upgrade

- package.json
- scripts/update-mosaic-packages.ts
- tsconfig.json
- yarn.lock
Added update-mosaic-packages.ts script with Yarn 2+ specific changes to bump up Axinom Mosaic libraries during releases.
> [AB#36987] Automatically bump mosaic libs in fe samples

- package.json
- src/scenario-registry.ts
- src/scenarios/image/ImagePreview/ImagePreview.tsx
- src/scenarios/image/ImagePreview/graphql-documents.ts
- src/scenarios/image/index.ts
- yarn.lock
> [AB#37446] Image preview scenario

- .adops/package-update.yml
- scripts/update-mosaic-packages.ts
- Add AzureDevOps pipeline to call ts script that updates Mosaic libs and commit back the changes to this repository
> feat: add pipeline to bump up mosaic lib versions

- src/scenarios/catalog-consumption/ListCatalogItems/ListCatalogItems.tsx
- src/scenarios/image/ImagePreview/ImagePreview.tsx
- src/scenarios/user-authentication/ResetPasswordWithAxAuth/ResetPasswordWithAxAuth.tsx
- src/scenarios/user-authentication/ShowUserInfo/ShowUserInfo.tsx
- src/scenarios/user-authentication/SignOutUser/SignOutUser.tsx
- src/scenarios/user-authentication/SignUpWithAxAuth/SignUpWithAxAuth.tsx
- src/scenarios/user-profile-management/SwitchActiveProfile/SwitchActiveProfile.tsx
- src/scenarios/video-playback/PlayProtectedVideo/PlayProtectedVideo.tsx
Minor improvements to the descriptions of some scenarios
> [AB#37769] Improvements to scenario descriptions

- package.json
- src/scenario-registry.ts
- src/scenarios/billing/SubscribeToSubscriptionPlan/SubscribeToSubscriptionPlan.tsx
- src/scenarios/billing/SubscribeToSubscriptionPlan/graphql-documents.ts
- src/scenarios/billing/SubscribeToSubscriptionPlan/paypal-utils.ts
- src/scenarios/billing/index.ts
- yarn.lock
This PR adds subscribe to subscription plan scenario to FE Samples.
> [AB#38228] Add subscribe to subscription plan scenario

- src/scenario-registry.ts
- src/scenarios/billing/ListUserSubscriptions/ListUserSubscriptions.tsx
- src/scenarios/billing/ListUserSubscriptions/graphql-documents.ts
- src/scenarios/billing/index.ts
Add list user subscriptions scenario
> [AB#38229] List user subscriptions scenario

- src/scenario-registry.ts
- src/scenarios/billing/ListSubscriptionPlansForUser/ListSubscriptionPlansForUser.tsx
- src/scenarios/billing/ListSubscriptionPlansForUser/graphql-documents.ts
- src/scenarios/billing/index.ts
List subscription plans for user scenario
> [AB#38227] List subscription plans for user scenario

- src/scenario-registry.ts
- src/scenarios/billing/ListSubscriptionPlansAnonymously/ListSubscriptionPlansAnonymously.tsx
- src/scenarios/billing/ListUserPaymentHistory/ListUserPaymentHistory.tsx
- src/scenarios/billing/ListUserPaymentHistory/graphql-documents.ts
- src/scenarios/billing/index.ts
- src/scenarios/video-playback/GetEntitlementMessage/GetEntitlementMessage.tsx
- src/scenarios/video-playback/PlayProtectedVideo/PlayProtectedVideo.tsx
List user payment plan history
> [AB#38230] - List user payment plan history

- package.json
- yarn.lock
> feat: [AB#38446] iteration 65 release

- src/scenario-registry.ts
- src/scenarios/billing/SubscribeToSubscriptionPlanPayPal/SubscribeToSubscriptionPlanPayPal.tsx
- src/scenarios/billing/SubscribeToSubscriptionPlanPayPal/paypal-utils.ts
- src/scenarios/billing/SubscribeToSubscriptionPlanStripe/SubscribeToSubscriptionPlanStripe.tsx
- src/scenarios/billing/UnsubscribeFromSubscriptionPlanPayPal/UnsubscribeFromSubscriptionPlanPayPal.tsx
- src/scenarios/billing/UnsubscribeFromSubscriptionPlanStripe/UnsubscribeFromSubscriptionPlanStripe.tsx
- src/scenarios/billing/index.ts
Add unsubscribe from subscription plan using Stripe scenario
> [AB#38633] Unsubscribe from subscription plan using Stripe scenario

- package.json
- yarn.lock
> [AB#39201] Deploy Iteration 69

- yarn.lock
addressing https://github.com/Axinom/mosaic-frontend-samples/security/dependabot/26
> chore: bump json5 to 2.2.2

- src/scenario-registry.ts
- src/scenarios/personalization/DataAdd/DataAdd.tsx
- src/scenarios/personalization/DataAdd/graphql-documents.ts
- src/scenarios/personalization/DataGet/DataGet.tsx
- src/scenarios/personalization/DataGet/graphql-documents.ts
- src/scenarios/personalization/DataRemove/DataRemove.tsx
- src/scenarios/personalization/DataRemove/graphql-documents.ts
- src/scenarios/personalization/index.ts
> [AB#38783, AB#38782, AB#38784] personalization scenario - Data add, get and remove scenarios

- src/scenarios/personalization/ArrayAddFavorites/ArrayAddFavorites.tsx
- src/scenarios/personalization/DataAdd/DataAdd.tsx
- src/scenarios/personalization/DataGet/DataGet.tsx
- src/scenarios/personalization/DataRemove/DataRemove.tsx
- src/scenarios/personalization/ProgressSet/ProgressSet.tsx
[[AB#38779](https://dev.azure.com/axinom/5e61ad7f-f562-45f3-8078-9ade7df639c1/_workitems/edit/38779), [AB#38778](https://dev.azure.com/axinom/5e61ad7f-f562-45f3-8078-9ade7df639c1/_workitems/edit/38778), [AB#38780](https://dev.azure.com/axinom/5e61ad7f-f562-45f3-8078-9ade7df639c1/_workitems/edit/38780)] personalization scenario - Handle error log display in add favorites scenario
> [AB#38779] Personalization scenarios - improve error logging

- package.json
- yarn.lock
Feature and package update for iteration 72.
> release: iteration 72

- src/scenarios/billing/SubscribeToSubscriptionPlan/graphql-documents.ts
Subscribe to Subscription Plan scenario will only list down active payment and subscription plans now
> [AB#40083] Show only active payment and subscription plans

- src/scenarios/catalog-consumption/GetSingleItem/GetSingleItem.tsx
- src/scenarios/user-authentication/ResetPasswordWithAxAuth/ResetPasswordWithAxAuth.tsx
- src/scenarios/user-authentication/SignInWithAxAuth/SignInWithAxAuth.tsx
- src/scenarios/user-authentication/SignInWithExternalIdps/SignInWithExternalIdps.tsx
- src/scenarios/user-authentication/SignUpWithAxAuth/SignUpWithAxAuth.tsx
- src/scenarios/user-profile-management/CreateProfile/CreateProfile.tsx
- src/scenarios/user-profile-management/DeleteProfile/DeleteProfile.tsx
- src/scenarios/user-profile-management/SwitchActiveProfile/SwitchActiveProfile.tsx
- src/scenarios/user-profile-management/UpdateProfile/UpdateProfile.tsx
- src/scenarios/video-playback/GetEntitlementMessage/GetEntitlementMessage.tsx
- src/scenarios/video-playback/PlayProtectedVideo/PlayProtectedVideo.tsx
- src/scenarios/video-playback/PlayUnprotectedVideo/PlayUnprotectedVideo.tsx
- yarn.lock
> [AB#37251] Make FE Samples reasonably responsive

- package.json
- yarn.lock
- Feature and bug fix release of iteration 75
> [AB#40325] release: iteration 75

- package.json
- yarn.lock
> [AB#40338] release: iteration 77

- .adops/pr-name-validation.yml
Adding a pipeline that validates that PR names include a reference to a work item.
> [AB#40688] ci: add PR title validation pipeline

- package.json
- yarn.lock
> [AB#41507] release: iteration 82

- .github/PULL_REQUEST_TEMPLATE.md
> [AB#41791] ci: updated PR template checklist

- package.json
- yarn.lock
> [AB#42110] Release: iteration 85

- package.json
- yarn.lock
> [AB#43142] Release: iteration 92

- src/scenarios/catalog-consumption/GetSingleItem/GetSingleItem.tsx
- src/scenarios/catalog-consumption/ListCatalogItems/ListCatalogItems.tsx
adds support for querying localized values of entities from the catalog service
> [AB#41881] support for localized values in catalog scenarios

- package.json
- yarn.lock
> [AB#43614] release: iteration 94

- .adops/pr-name-validation.yml
- src/scenarios/catalog-consumption/ListCatalogItems/graphql-documents.ts
The frontend sample to list channel entities in the catalog service got extended to list also the playlists in the "All catalog service items". For the "All Channels" action it also lists the program items and reads the data from the corresponding movie or episode (if that one was published).
Publish a channel with at least one playlist and at elast one program item. Check that they are loaded correctly. When the corresponding movie/episode is not published it should show "null" in that place - otherwise the movie/episdoe title. Please also test to change the title of a program item and the localizations.
> [AB#44954] Get playlists for channel

- .adops/pr-name-validation.yml
> [AB#44981] fix: use var group for gh automation

- package.json
- yarn.lock
> [AB#45001][AB#45003][AB#44729] chore(release): iteration 101

- package.json
- yarn.lock
> [AB#48747][AB#48757][AB#48761] releases: iteration 118

- .adops/build-pipeline.yml
- .adops/package-update.yml
- .adops/pr-pipeline.yml
> [AB#49539] chore(upgrade): switch node version from 18 to 22
